In [2]:
#Basic If-Else Statements:
#Q1. Write a Python program to check if a given number is positive or negative.

n1 = int(input("enter the number"))

if n1 > 0 :
    print("Postive Number")
else: 
    print("negtive number")
    
#enter the number -4
#negtive number    

enter the number -4


negtive number


In [5]:
#Q2. Create a program that determines if a person is eligible to vote based on their age.

age = int(input("enter your age"))

if age >= 18 :
    print("You can cast the vote")
else: 
    print("You are not eligible for vote")
#enter your age 34
#You can cast the vote    

enter your age 34


You can cast the vote


In [10]:
#Q3. Develop a program to find the maximum of two numbers using if-else statements.

a, b = input("Enter two numbers :").split()

if int(a) > int(b):
    print("max number is ", a)
else :
    print("max number is " , b)

#Enter two numbers : 4 6
#max number is  6

Enter two numbers : 4 6


max number is  6


In [14]:
#Q4. Write a Python script to classify a given year as a leap year or not.

year  = input("enter the year")

if (int(year) % 4 == 0 and int(year) % 100 != 0) or (int(year) % 400 == 0) :
    print("leap year")
else: 
    print("not a leap year")


enter the year 2021


not a leap year


In [17]:
#Q5. Create a program that checks whether a character is a vowel or a consonant.

a = input("input the charater")

if a.lower() in ('a','e','i','o','u') :
    print("character is Vowel")
else: 
    print("character is consonant")
    
#input the charater D
#character is consonant
    

input the charater D


character is consonant


In [21]:
#Q6. Implement a program to determine whether a given number is even or odd.

num  = int(input("enter the number"))

if num%2 == 0 :
    print("number is even")
else: 
    print("number is odd")
#enter the number 9
#number is odd    

enter the number 9


number is odd


In [24]:
#Q7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

num  = int(input("enter the number"))

if num > 0 :
    print("abs value of the number : ", num)
else : 
    print("abs value of the number : ", num*-1)
#enter the number -5
#abs value of the number :  5    

enter the number -5


abs value of the number :  5


In [57]:
#Q8. Develop a program that determines the largest of three given numbers using if-else statements.

num1 , num2 , num3  = map(int, (input("enter the three numbers : ").split()))

if num1 >= num2 :
    if num2 >=num3:
        print("largest number is ", num1)
    else :
        print("largest number is " , num3)
elif num2 >= num3 :
    print("largest numebr is ", num2)    
else :
    print("largest number is ", num3)

#enter the three numbers :  4 5 1
#largest number is  5    

enter the three numbers :  4 5 1


largest numebr is  5


In [87]:
#Q9. Create a program that checks if a given string is a palindrome.

str1 = input("enter a string")


if str1[:round(len(str1)/2)+1:] == str1[:round(len(str1)/2)-1:-1] :
    print("string is palindrome")
else: 
    print("string is not palindrome")
#enter a string aanaa
#string is palindrome  

enter a string aanaa


string is palindrome


In [94]:
#Q10. Write a Python program to calculate the grade based on a student's score.

grade = int(input("Enter the score"))

if grade >= 85 :
    print("A+ Grade")
elif grade >= 70 and grade < 85:
    print("A Grade")
elif grade >= 60 and grade < 70:
    print("B Grade")
elif grade >= 45 and grade < 60:
    print("C Grade")
else :
    print("D Grade")
    
#Enter the score 89
#A+ Grade    

Enter the score 89


A+ Grade


In [95]:
#Q11. Write a program to find the largest among three numbers using nested if-else statements.

num1 , num2 , num3  = map(int, (input("enter the three numbers : ").split()))

if num1 >= num2 :
    if num2 >=num3:
        print("largest number is ", num1)
    else :
        print("largest number is " , num3)
elif num2 >= num3 :
    print("largest numebr is ", num2)    
else :
    print("largest number is ", num3)

#enter the three numbers :  4 7 9
#largest number is  9    

enter the three numbers :  4 7 9


largest number is  9


In [100]:
#Q12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

a, b,c = map(int, (input("enter the 3 sides of trangle").split()))

if a == b and b == c:
    print("triangle is equilateral")
elif a==b or b==c or a == c:
    print("traingle is isocceles")
else :
    print("traingle is scalene")
    
#enter the 3 sides of trangle 2 3 2
#traingle is isocceles             

enter the 3 sides of trangle 2 3 2


traingle is isocceles


In [109]:
#Q13. Develop a program that checks if a year is a leap year and also if it is a century year.

year  = int(input("enter the year"))

cent = round(year/100)
if (int(year) % 4 == 0 and int(year) % 100 != 0) or (int(year) % 400 == 0) :
    print("leap year and Century is ", cent)
else: 
    print("not a leap year and century is ", cent)

#enter the year 1995
#not a leap year and century is  20    


enter the year 1995


not a leap year and century is  20


In [112]:
#Q14. Write a Python script to determine if a number is positive, negative, or zero.

num1 = int(input("enter the number"))

if num1 > 0 :
    print("mumber is positive")
elif num1 < 0:
    print("number is negtive")
else :
    print("number is zero")

#enter the number -1
#number is negtive    

enter the number -1


number is negtive


In [124]:
#Q15. Create a program to check if a person is a teenager (between 13 and 19 years old).

age= int(input("enter the age"))

if  13 <= age <= 19:
    print("teenage")
else :
    print("not a teenager")

#enter the age 14
#teenage    

enter the age 14


teenage


In [129]:
#Q16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

angle = int(input("Enter your angle"))

if angle >= 0 and angle < 90 :
    print("acute angle")
elif angle == 90 :
    print("right angle")
elif angle > 90 and angle < 180 :
    print("obtuse angle")
#Enter your angle 123
#obtuse angle    

Enter your angle 123


obtuse angle


In [139]:
#Q17. Write a Python program to calculate the roots of a quadratic equation.

import math
a,b,c = map(int,(input("enter the three numbers").split()))
            
d = math.sqrt(abs(b*b - 4*a*c))
            
e = (-b + d )/2*a
f = (-b - d )/2*a
            
print(f' Real number is {e}, imaginary number is {f} ')            

#enter the three numbers 3 4 6
#Real number is 5.224972160321824, imaginary number is -17.224972160321823 
            

enter the three numbers 3 4 6


 Real number is 5.224972160321824, imaginary number is -17.224972160321823 


In [141]:
#Q18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2 for Tuesday, etc.)

num1  = int(input("Please enter the number betwwen 1 to 7 :"))

if num1 == 1 : 
    print("Monday")
elif  num1 == 2 :  
    print("Tueday")
elif  num1 == 3 :  
    print("Wednesday")
elif  num1 == 4 :  
    print("Thursday")
elif  num1 == 5 :  
    print("Friday")
elif  num1 == 6 :  
    print("Saturday")
elif  num1 == 7 :  
    print("Sunday")
else: 
    print("Enter the correct number")
    
#Please enter the number betwwen 1 to 7 : 3
#Wednesday    

Please enter the number betwwen 1 to 7 : 3


Wednesday


In [142]:
#Q19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

year  = input("enter the year")

if (int(year) % 4 == 0 and int(year) % 100 != 0) or (int(year) % 400 == 0) :
    print("leap year")
else: 
    print("not a leap year")

#enter the year 2000
#leap year    

enter the year 2000


leap year


In [6]:
#Q20. Develop a program that checks if a given number is prime or not using nested if-else statements.

num1 = int(input("enter the number"))

if num1 == 1 :
    print("not a prime number")
elif num1 > 1:
    for i in range(2,num1):
        if num1%i == 0 :
            print(num1, "is not a prime number")
            break
    else: 
        print("not a prime number")

#enter the number 12
#12 is not a prime number        

enter the number 12


12 is not a prime number


In [6]:
#Q23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using elif statements.

height = float(input("Enter your height in meters: "))
weight = float(input("Enter your weight in kg: "))

BMI = weight / (height*height)
print(BMI)

if BMI <= 18.4:
    print("You are underweight.")
elif BMI <= 24.9:
    print("You are healthy.")
elif BMI <= 29.9:
    print("You are over weight.")
elif BMI <= 34.9:
    print("You are severely over weight.")
elif BMI <= 39.9:
    print("You are obese.")
else:
    print("You are severely obese.")
 
#Enter your height in meters:  1.65
#Enter your weight in kg:  66
#24.242424242424246
#You are healthy.

Enter your height in meters:  1.65
Enter your weight in kg:  66


24.242424242424246
You are healthy.


In [10]:
#Q25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif statements.

char1 = input("enter the character")

if char1.isalpha() == True:
    if char1.islower() == True:
        print("Character is looercase")
    else: 
        print("character is uppercase")
else: 
    print("character is sepecial one")
    
#enter the character @
#character is sepecial one

enter the character @


character is sepecial one


In [5]:
#Q27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements.

bill_unit = float(input("Enter the electricity Bill Units : "))

if bill_unit  <= 60 :
    elec_bill = bill_unit * 0
elif bill_unit  > 60 and bill_unit <= 100 :
    elec_bill = bill_unit * 1.2
elif bill_unit  > 100 and bill_unit <= 200 :
    elec_bill = bill_unit * 1.8
elif bill_unit  > 200 and bill_unit <= 400 :
    elec_bill = bill_unit * 2.5
else :
    elec_bill = bill_unit * 4
    
print("bill units are" , bill_unit)
print("Electricity Bill " , elec_bill) 
    
#Enter the electricity Bill Units :  410
#bill units are 410.0
#Electricity Bill  1640.0    
    


Enter the electricity Bill Units :  410


bill units are 410.0
Electricity Bill  1640.0


In [10]:
#Q28 Write a Python script to determine the season based on a user-provided month using elif statements.

month = input("please enter the month" )

if month in ('feb' , 'march') :
    print("spring season")
elif month in ('apr', 'may'):
    print("summer season")
elif month in ('jun', 'july', 'sept'):
    print("monson season")
elif month in ('oct', 'nov'):
    print("autumn season")
elif month in ('dec','jan','feb'):
    print("winter Season")
#please enter the month march
#spring season

please enter the month march


spring season


In [1]:
#Q29 Create a program that simulates a basic ATM transaction menu.

user_pin = 1234
user_balance = 97432.50
user_name = "Ms. ABC"
print("Welcome to your bank account", user_name, end = "\n\n")
choice = 9
while (True):
    print("0. Logout and Exit")
    print("1. View Account Balance")
    print("2. Withdraw Cash")
    print("3. Deposit Cash")
    print("4. Change PIN")
    print("5. Return Card")
    choice = int(input("Enter number to proceed > "))
    print("\n\n")
    if choice == 0 :
        print("Thank You for using.\n\n ")
        break
    elif choice in (1,2,3,4,5):
        num_of_tries = 3
        while (num_of_tries!=0):
            input_pin = int(input("Please enter your 4-digit PIN > "))
        
            if input_pin == user_pin:
                print("Account auhtorized!\n\n")
                
                if choice == 1:
                    print("Loading Account Balance...")
                
                    print("Your current balance is Rs.", user_balance, end = "\n\n\n")
                    break
                elif choice == 2:
                    print("Opening Cash Withdrawal...")
                    

                    while(True):
                        withdraw_amt = float(input("Enter the amount you wish to withdraw > "))

                        if withdraw_amt>user_balance:
                            print("Can't withdraw Rs.", withdraw_amt)
                            print("Please enter a lower amount!")
                            continue

                        else:
                            print("Withdrawing Rs.", withdraw_amt)
                            confirm = input("Confirm? Y/N > ")
                            if confirm in ('Y', 'y'):
                                user_balance-=withdraw_amt
                                print("Amount withdrawn - Rs.", withdraw_amt)
                                print("Remaining balance - Rs.", user_balance, end = "\n\n\n")
                                break

                            else:
                                print("Cancelling transaction...")
                                
                                print("Transaction Cancelled!\n\n")
                                break
                    
                    break

                elif choice == 3:
                    print("Loading Cash Deposit...")
                    

                    deposit_amt = float(input("Enter the amount you wish to deposit > "))
                    print("Depositing Rs.", deposit_amt)
                    confirm = input("Confirm? Y/N > ")
                    if confirm in ('Y', 'y'): 
                        user_balance+=deposit_amt
                        print("Amount deposited - Rs.", deposit_amt)
                        print("Updated balance - Rs.", user_balance, end = "\n\n\n")
                    else:
                        print("Cancelling transaction...")
                        
                        print("Transaction Cancelled!\n\n")
                                
                    break

                    
                elif choice == 4:
                    print("Loading PIN Change...")
                    

                    pin_new = int(input("Enter your new PIN > "))

                    print("Changing PIN to", pin_new)
                    confirm = input("Confirm? Y/N > ")
                    if confirm in ('Y', 'y'): 
                        user_pin = pin_new
                        print("PIN changed successfully! \n\n")
                    else:
                        print("Cancelling PIN change...")
                        
                        print("Process Cancelled!\n\n")

                    break

                else:
                    print("Loading Card Return...")
                    

                    print("Returning your ATM Card")
                    confirm = input("Confirm? Y/N > ")
                    if confirm in ('Y', 'y'): 
                        print("Card returned successfully! \n\n")
                    else:
                        print("Cancelling process...")
                        
                        print("Process Cancelled!\n\n")

                    break

            else:
                num_of_tries-=1 
                print("PIN incorrect! Number of tries left -", num_of_tries, end = "\n\n")   

        else:
            print("Exiting...")
            
            print("You have been logged out. Thank you!\n\n")
            break
            

    else:
        print("Invalid input!")
        print("Enter 0 to Logout and Exit!")
        continue    

Welcome to your bank account Ms. ABC

0. Logout and Exit
1. View Account Balance
2. Withdraw Cash
3. Deposit Cash
4. Change PIN
5. Return Card


Enter number to proceed >  1


Please enter your 4-digit PIN >  1234


Account auhtorized!


Loading Account Balance...
Your current balance is Rs. 97432.5


0. Logout and Exit
1. View Account Balance
2. Withdraw Cash
3. Deposit Cash
4. Change PIN
5. Return Card


Enter number to proceed >  0





Thank You for using.

 


In [5]:
#Q30Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

num1 = float(input("Please enter the first number"))
num2 = float(input("please enter the second number"))

choice = 0

while(True):
    print("\n")
    print(" '+' for addition")
    print(" '-' for subtraction")
    print(" '*' for multiplicaton")
    print(" '/' for division")
    print(" '%' for moduls")
    print(" '**' for Power")
    print(" '0' for main menu")
    print(" Enter any other key to exit")
    print("\n")    
    choice= input("enter your choice > " )
    print("\n")
    if choice == '+' :
        print("addition is :" , num1 + num2) 
    elif choice == '-' :    
        print("subtraction is :" , num1 - num2)
    elif choice == '*' :    
        print("multiplicaton is :" , num1 * num2)
    elif choice == '/' :    
        print("division is :" , num1 / num2)
    elif choice == '%' :    
        print("moduls is :" , num1 % num2)
    elif choice == '**' :    
        print("power is :" , num1 ** num2)  
    elif choice == '0' :    
        continue    
    else:
        print("Exit from the program. Thank You for using.")
        break
        

Please enter the first number 3
please enter the second number 4




 '+' for addition
 '-' for subtraction
 '*' for multiplicaton
 '/' for division
 '%' for moduls
 '**' for Power
 '0' for main menu
 Enter any other key to exit




enter your choice >  +




addition is : 7.0


 '+' for addition
 '-' for subtraction
 '*' for multiplicaton
 '/' for division
 '%' for moduls
 '**' for Power
 '0' for main menu
 Enter any other key to exit




enter your choice >  e




Exit from the program. Thank You for using.


In [19]:
#Q31 Create a program that calculates the income tax based on the user's income and tax brackets.

income = int(input("Enter your yearly income : "))

if income <= 250000 :
    tax = 0
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)

elif income > 250000  and income <= 500000:
    tax = (income * 5) / 100
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)
    
elif income > 500000  and income <= 750000:
    tax = ((income - 500000)*10)/100 + 12500
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)
    
elif income <= 1000000:
    tax = ((income - 750000)*15)/100 + 37500
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)

elif income <= 1250000:
    tax = ((income - 1000000)*20)/100 + 75000
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)

elif income > 1500000:
    tax = ((income - 1000000)*25)/100 + 125000
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)
else:
    tax = ((income - 1500000)*30)/100 + 187500
    print("Total Income is :"  , income)
    print("Tax on the Income : "  , tax)
    
#Enter your yearly income :  1200000
#Total Income is : 1200000
#Tax on the Income :  115000.0    
    

Enter your yearly income :  1200000


Total Income is : 1200000
Tax on the Income :  115000.0


In [12]:
#Q32 Develop a program that generates a random password based on user preferences (length, complexity).

import random 
import array

length = int(input("Enter the lenght for the password " ))
compl  = input("What is the complexity you perfer (low/midium/high " )

DIGITS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] 
LOCASE_CHARACTERS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
                     'i', 'j', 'k', 'm', 'n', 'o', 'p', 'q',
                     'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
                     'z']
 
UPCASE_CHARACTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                     'I', 'J', 'K', 'M', 'N', 'O', 'P', 'Q',
                     'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
                     'Z']
 
SYMBOLS = ['@', '#', '$', '%', '=', ':', '?', '.', '/', '|', '~', '>',
           '*', '(', ')', '<']
 
# combines all the character arrays above to form one array
COMBINED_LIST0 = DIGITS + UPCASE_CHARACTERS 
COMBINED_LIST1 = DIGITS + UPCASE_CHARACTERS + LOCASE_CHARACTERS 
COMBINED_LIST2 = DIGITS + UPCASE_CHARACTERS + LOCASE_CHARACTERS + SYMBOLS


rand_combined_list0 = random.choice(COMBINED_LIST0)
rand_combined_list1 = random.choice(COMBINED_LIST1)
rand_combined_list2 = random.choice(COMBINED_LIST2)

random.shuffle(rand_combined_list0) 
random.shuffle(rand_combined_list1) 
random.shuffle(rand_combined_list2) 

temp_pass_0 = array.array('u', rand_combined_list0)
temp_pass_1 = array.array('u', rand_combined_list1)
temp_pass_2 = array.array('u', rand_combined_list2)

password = ''
n = 0
while ( n <= length):
    if compl == 'low':
        for i in temp_pass_0 :
            password = password + i
            n = n + 1
    elif  compl == 'midium':
        for i in temp_pass_1:
            password = password + i
            n = n + 1
            
    elif  compl == 'high':
        for i in temp_pass_2:
            password = password + i
            n = n + 1
            
print(password)

Enter the lenght for the password  8
What is the complexity you perfer (low/midium/high  high


FFFFFFFFF


In [14]:
#Q33 Create a program that validates a password based on complexity rules (length, characters, etc.).

def pass_check():
    a = input("Add your Password" )
    spl= " /\'  "
    if len(a) >= 8 and len(a) <= 32 :
        if  (a[0].isalpha() == True) and (a[0].isupper() == True or a[0].islower() == True ):  
            for i in spl:
                if a.find(i) != -1:
                    print('Invalid Password due to password contains specail characters "/\'" and space. ')
                    break
            else :
                print("Password is correct")
                    
        else:
            print("Invalid Password - First letter should be start with lower or upper case letter ")
    else: 
         print("Invalid Pasword- It should be more than 8 and less than 32 characters long")
        
pass_check()        
#Add your Password vikas@sharma
#Password is correct    
    

Add your Password vikas@sharma


Password is correct


In [1]:
#Q34. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

answer_ppt = []
counter= 1
point_table = 0
while(True):
    print("\n\n")
    print(" Welcome to the Quiz Show ")
    print(" Rules of the Quiz.")
    print(" You will see multiple-Choice question on the screen")
    print(" Every Correct answer scoring 5 points. ")
    print(" Total 10 questions will be ask , cut off/pass percentage is 80%")
    print("\n\n")
    
    while (counter <=10):
        
        if counter == 1:    
            print("\n")
            print("Q.1 Who is the Prime minister of India")
            print("\n")
            print("a. Rahul  b. Modi c. ABC d. kejriwal")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'b':
                point_table = 5
            else :
                point_table = 0
                            
        elif counter == 2:   
            print("\n")
            print("Q.2 What is the capital of India.")
            print("\n")
            print("a. delhi  b. mumbai c. channai d. kolkata")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'a':
                point_table = point_table + 5 
            else :
                point_table = point_table

        elif counter == 3:    
            print("\n")
            print("Q.3 Where is ICC World Cup 2023 held on?")
            print("\n")
            print("a. Srilanka  b. Australia c. India d. Nepal")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'c':
                point_table = point_table + 5 
            else :
                point_table = point_table
            
        elif counter == 4:    
            print("\n")
            print("Q.4 Who is first prime minister of India")
            print("\n")
            print("a. Nehru  b. Indra c. Modi d. Rahul")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'a':
                point_table = point_table + 5 
            else :
                point_table = point_table            
            
            
        elif counter == 5:    
            print("\n")
            print("Q.5 What is (2 + 4 ) is -")
            print("\n")
            print("a. 5  b. 2 c. 6 d. 4")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'c':
                point_table = point_table + 5 
            else :
                point_table = point_table            
                        
        elif counter == 6:    
            print("\n")
            print("Q.6 How many colors in rainbow?")
            print("\n")
            print("a. 3  b. 6 c. 8  d. 7")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'd':
                point_table = point_table + 5 
            else :
                point_table = point_table            
                        
        elif counter == 7:    
            print("\n")
            print("Q.7 What is the biggest animal on the earth?")
            print("\n")
            print("a. Elephant  b. Cow c. Loin d. Horse")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'a':
                point_table = point_table + 5 
            else :
                point_table = point_table            
                        
        elif counter == 8:    
            print("\n")
            print("Q.8 Whar is the name of Arjun's Son?")
            print("\n")
            print("a. gathotcach  b. abhimanu c. ram d. sham")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'b':
                point_table = point_table + 5 
            else :
                point_table = point_table            
                        
        elif counter == 9:    
            print("\n")
            print("Q.9. Chandrayaan 3 is on which sub-plannet?")
            print("\n")
            print("a. china  b. Earth c. Moon d. mars")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'c':
                point_table = point_table + 5 
            else :
                point_table = point_table            
                        
        elif counter == 10:    
            print("\n")
            print("Q.10 what is (5 + 6 )= ")
            print("\n")
            print("a. 10  b. 9 c. 11 d. 12")
            print("\n\n")
            ans_ppt = input("Please enter your answer in (a,b,c or d)  > ")
            counter = counter + 1
            answer_ppt.append(ans_ppt)
            if ans_ppt == 'c':
                point_table = point_table + 5 
            else :
                point_table = point_table             
            
             
            win = (point_table /50)*100        
            print("\n")
            print("final Scores is :- ", point_table )
            print("Answers given by the participant : " , answer_ppt)
            if win >= 80:
                print("Congratulations. You won the contest with percent >>> " , win)
            else :
                print("You lost the contest. your percentage is >>> " , win)
                
            
            
    else : 
        print("\n")
        print("Quiz is over")
        print("Thank You.")
        break
        




 Welcome to the Quiz Show 
 Rules of the Quiz.
 You will see multiple-Choice question on the screen
 Every Correct answer scoring 5 points. 
 Total 10 questions will be ask , cut off/pass percentage is 80%





Q.1 Who is the Prime minister of India


a. Rahul  b. Modi c. ABC d. kejriwal





Please enter your answer in (a,b,c or d)  >  b




Q.2 What is the capital of India.


a. delhi  b. mumbai c. channai d. kolkata





Please enter your answer in (a,b,c or d)  >  a




Q.3 Where is ICC World Cup 2023 held on?


a. Srilanka  b. Australia c. India d. Nepal





Please enter your answer in (a,b,c or d)  >  a




Q.4 Who is first prime minister of India


a. Nehru  b. Indra c. Modi d. Rahul





Please enter your answer in (a,b,c or d)  >  a




Q.5 What is (2 + 4 ) is -


a. 5  b. 2 c. 6 d. 4





Please enter your answer in (a,b,c or d)  >  c




Q.6 How many colors in rainbow?


a. 3  b. 6 c. 8  d. 7





Please enter your answer in (a,b,c or d)  >  a




Q.7 What is the biggest animal on the earth?


a. Elephant  b. Cow c. Loin d. Horse





Please enter your answer in (a,b,c or d)  >  d




Q.8 Whar is the name of Arjun's Son?


a. gathotcach  b. abhimanu c. ram d. sham





Please enter your answer in (a,b,c or d)  >  b




Q.9. Chandrayaan 3 is on which sub-plannet?


a. china  b. Earth c. Moon d. mars





Please enter your answer in (a,b,c or d)  >  a




Q.10 what is (5 + 6 )= 


a. 10  b. 9 c. 11 d. 12





Please enter your answer in (a,b,c or d)  >  c




final Scores is :-  30
Answers given by the participant :  ['b', 'a', 'a', 'a', 'c', 'a', 'd', 'b', 'a', 'c']
You lost the contest. your percentage is >>>  60.0


Quiz is over
Thank You.


In [15]:
#Q35 Create a program that sorts three numbers in ascending order using conditional statements.

a,b,c = map(int,(input("Please enter the three numbers ").split()))

list1 = []
if a < b and a < c:
    if b < c:
        x, y,z = a,b,c
    else:
        x, y,z = a ,c, b
if  b < a and b < c:
    if a < c:   
        x,y,z=b,a,c
    else:
        x,y,z=b,c,a

if  c < a and c < b:
    if a < b:   
        x,y,z=c,a,b
    else:
        x,y,z=c,b,a
 
        
print(x,y,z)        
             
            

Please enter the three numbers  3 2 1


1 2 3


In [1]:
#Q40 Develop a program that performs matrix addition and subtraction based on user input.
import numpy as np
m1 = np.array([[1, 3, 4], [8, 5, 6]])
m2 = np.array([[8, 6, 9], [9, 0, 6]])

print("Add Matrix:")
a = np.add(m1, m2)
print(a)

print("Subtract Matrix:")
b = np.subtract(m2, m1)
print(b)

'''
Add Matrix:
[[ 9  9 13]
 [17  5 12]]
Subtract Matrix:
[[ 7  3  5]
 [ 1 -5  0]]
 
 '''

Add Matrix:
[[ 9  9 13]
 [17  5 12]]
Subtract Matrix:
[[ 7  3  5]
 [ 1 -5  0]]


In [ ]:
# Program to add two matrices using nested loop
